name: Deploy to Vercel

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install Vercel CLI
      run: npm install --global vercel@latest
      
    - name: Deploy to Vercel
      run: |
        echo "sqlite:////tmp/ecommerce.db" | vercel env add DATABASE_URL production --token=${{ secrets.VERCEL_TOKEN }} || true
        vercel --token=${{ secrets.VERCEL_TOKEN }} --prod 